/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view1;

import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.SQLException;
import java.util.List;


/**
 *
 * @author ravinaeka
 */
public class formUjiKualitasAir extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(formUjiKualitasAir.class.getName());


    public formUjiKualitasAir() throws SQLException {
        initComponents(); 
        setLocationRelativeTo(null); 
        setResizable(false);         
        setPreferredSize(new java.awt.Dimension(1020, 600)); 
        pack();
        
        jTextField1.setText("YYYY-MM-DD");
        jTextField1.setForeground(java.awt.Color.GRAY);

        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {
                if (jTextField1.getText().equals("YYYY-MM-DD")) {
                    jTextField1.setText("");
                    jTextField1.setForeground(java.awt.Color.BLACK);
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
                if (jTextField1.getText().isEmpty()) {
                    jTextField1.setText("YYYY-MM-DD");
                    jTextField1.setForeground(java.awt.Color.GRAY);
                }
            }
        });
        isiComboBoxSumberAir();
        muatDataKualitasAir();
    }
        private void muatDataKualitasAir() {
        try {
        dao.kualitasAirDao dao = new dao.kualitasAirDao();
        java.util.List<model.kualitasAir> list = dao.getAll();

        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(
            new Object[]{"ID", "Nama Sumber", "Tanggal Uji", "pH", "Status"}, 0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) { return false; }
        };

        for (model.kualitasAir k : list) {
            model.addRow(new Object[]{
                k.getIdKualitas(),
                k.getNamaSumber(),
                k.getTanggalUji(),
                String.format("%.2f", k.getPh()),
                k.getStatusKelayakan()
            });
        }

        jTable1.setModel(model);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.getTableHeader().setResizingAllowed(false);

    } catch (SQLException e) {
        javax.swing.JOptionPane.showMessageDialog(
            this,
            "Gagal memuat data kualitas air:\n" + e.getMessage(),
            "Kesalahan Database",
            javax.swing.JOptionPane.ERROR_MESSAGE
        );
    }

    }
     private void isiComboBoxSumberAir() throws SQLException {
    try {
        dao.sumberAirDao dao = new dao.sumberAirDao();
        java.util.List<model.sumberAir> list = dao.getAll();

        jComboBox1.removeAllItems();
        for (model.sumberAir s : list) {
            jComboBox1.addItem(s.getIdSumber() + " - " + s.getNamaSumber() + " - " + s.getLokasi());
        }

    } catch (SQLException e) {
        javax.swing.JOptionPane.showMessageDialog(
            this,
            "Gagal memuat data sumber air:\n" + e.getMessage(),
            "Kesalahan Database",
            javax.swing.JOptionPane.ERROR_MESSAGE
        );
    }
}
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(166, 166, 166));
        jButton1.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jButton1.setText("Kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 550, -1, -1));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        jLabel2.setText("UJI KUALITAS AIR");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel3.setText("Masukkan Tanggal Uji :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nama Sumber ", "Tanggal Uji", "PH", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 210, 480, 330));

        jButton2.setBackground(new java.awt.Color(108, 153, 194));
        jButton2.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jButton2.setText("Uji Kualitas Air");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, 150, -1));

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, 280, 30));

        jTextField1.setForeground(new java.awt.Color(128, 128, 128));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, 280, 30));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel4.setText("Pilih Sumber Air :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view1/eimg form uji kualitas air.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1026, 580));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel5.setText("Pilih Sumber Air");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TO   DO add your handling code here:
        new menuAdmin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                                                    
        try {
            String selected = (String) jComboBox1.getSelectedItem();
            if (selected == null || selected.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Pilih sumber air terlebih dahulu!",
                    "Peringatan",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }

            int idSumber = Integer.parseInt(selected.split(" - ")[0]);
            String tanggalText = jTextField1.getText().trim();

            if (tanggalText.isEmpty() || tanggalText.equals("YYYY-MM-DD")) {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Masukkan tanggal uji (format: yyyy-MM-dd)!",
                    "Input Salah",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }

            java.sql.Date sqlDate = java.sql.Date.valueOf(tanggalText);

            dao.sumberAirDao daoSumber = new dao.sumberAirDao();
            model.sumberAir sumber = daoSumber.getById(idSumber);

            if (sumber == null) {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Data sumber air tidak ditemukan di database!",
                    "Kesalahan",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            double basePh;
            basePh = switch (sumber.getJenisSumber().toLowerCase()) {
                case "waduk" -> 7.2;
                case "sungai" -> 7.0;
                case "sumur" -> 6.8;
                case "spam" -> 7.5;
                case "mata air" -> 7.3;
                case "danau" -> 7.1;
                case "bendung" -> 6.9;
                default -> 7.0;
            };

            double ph = basePh + (Math.random() - 0.5) * 0.8;
            ph = Math.round(ph * 100.0) / 100.0;

            String status = (ph >= 6.5 && ph <= 8.5) ? "Layak" : "Tidak Layak";

            javax.swing.JLabel hasilLabel = new javax.swing.JLabel(
                String.format("<html><div style='text-align:center;'>"
                    + "<b>Uji kualitas air selesai!</b><br>"
                    + "Jenis: %s<br>"
                    + "Nilai pH: %.2f<br>"
                    + "<span style='color:%s;font-size:14px;'><b>Status: %s</b></span>"
                     + "</div></html>",
                    sumber.getJenisSumber(),
                    ph,
                    status.equals("Layak") ? "green" : "red",
                    status)
            );
            hasilLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.JOptionPane.showMessageDialog(
            this,
            hasilLabel,
            "Hasil Uji Kualitas Air",
            javax.swing.JOptionPane.INFORMATION_MESSAGE
        );

            model.kualitasAir kualitas = new model.kualitasAir();
            kualitas.setTanggalUji(sqlDate);
            kualitas.setPh(ph);
            kualitas.setStatusKelayakan(status);
            kualitas.setIdSumber(idSumber);

            dao.kualitasAirDao daoKualitas = new dao.kualitasAirDao();
            daoKualitas.insert(kualitas);

            muatDataKualitasAir();

            jTextField1.setText("YYYY-MM-DD");
            jTextField1.setForeground(java.awt.Color.GRAY);

        } catch (IllegalArgumentException e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Format tanggal salah! Gunakan yyyy-MM-dd (contoh: 2025-10-30).",
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        } catch (HeadlessException e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Terjadi kesalahan: " + e.getMessage(),
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Kesalahan database: " + ex.getMessage(),
                "Error Database",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        jTextField1 = new javax.swing.JTextField();
        jTextField1.setForeground(new java.awt.Color(128, 128, 128));
        jTextField1.setText("YYYY-MM-DD");

        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (jTextField1.getText().equals("YYYY-MM-DD")) {
                    jTextField1.setText("");
                    jTextField1.setForeground(new java.awt.Color(0, 0, 0));
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (jTextField1.getText().isEmpty()) {
                    jTextField1.setForeground(new java.awt.Color(128, 128, 128));
                    jTextField1.setText("YYYY-MM-DD");
                }
            }
});

    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    String selected = (String) jComboBox1.getSelectedItem();
    if (selected != null) {
        String idText = selected.split(" - ")[0]; 
        int idSumber = Integer.parseInt(idText);
        System.out.println("ID sumber terpilih: " + idSumber);
    }
    }//GEN-LAST:event_jComboBox1ActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new formUjiKualitasAir().setVisible(true);
            } catch (SQLException ex) {
                System.getLogger(formUjiKualitasAir.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}


