/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view1;

import java.sql.SQLException;


/**
 *
 * @author ravinaeka
 */
public class formSumberAir extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(formSumberAir.class.getName());

    /**
     * Creates new form formSumberAir
     */
    public formSumberAir() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        
        jComboBox1.removeAllItems();
        jComboBox1.addItem("Aktif");
        jComboBox1.addItem("Tidak Aktif");
        jComboBox1.setSelectedIndex(-1);
        muatDataSumberAir();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        jLabel2.setText("SUMBER AIR");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel3.setText("Nama:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel4.setText("Jenis:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel5.setText("Status:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 70, -1, -1));

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel6.setText("Lokasi:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 110, -1, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 110, 160, 30));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, 160, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID ", "Nama ", "Jenis ", "Status", "Lokasi"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 210, 490, 330));

        jButton1.setBackground(new java.awt.Color(166, 166, 166));
        jButton1.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jButton1.setText("Kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 550, -1, -1));

        jButton2.setBackground(new java.awt.Color(108, 153, 194));
        jButton2.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jButton2.setText("Tambah Sumber");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 170, -1, -1));

        jButton3.setBackground(new java.awt.Color(108, 153, 194));
        jButton3.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jButton3.setText("Edit Sumber");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 170, -1, -1));

        jButton4.setBackground(new java.awt.Color(108, 153, 194));
        jButton4.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jButton4.setText("Hapus Sumber");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 170, -1, -1));

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 70, 160, 30));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Waduk", "Sungai", "Sumur", "SPAM", "Mata Air", "Danau", "Bendung" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 110, 160, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view1/eimg form sumber air.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1026, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new menuAdmin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                                       
        try {
            if (jTextField3.getText().trim().isEmpty() ||
                jComboBox2.getSelectedItem() == null ||
                jTextField2.getText().trim().isEmpty() ||
                jComboBox1.getSelectedItem() == null) {

                javax.swing.JOptionPane.showMessageDialog(this,
                    "Semua field termasuk status harus diisi!",
                    "Input Tidak Lengkap",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }

            dao.sumberAirDao dao = new dao.sumberAirDao();
            String namaSumber = jTextField3.getText().trim();

            if (dao.isNamaSumberExist(namaSumber)) {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Nama sumber \"" + namaSumber + "\" sudah terdaftar!\nTidak boleh duplikat.",
                    "Data Duplikat",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }

            model.sumberAir sumber = new model.sumberAir();
            sumber.setNamaSumber(namaSumber);
            sumber.setJenisSumber((String) jComboBox2.getSelectedItem());
            sumber.setStatus((String) jComboBox1.getSelectedItem());
            sumber.setLokasi(jTextField2.getText().trim());

            dao.insert(sumber);

            javax.swing.JOptionPane.showMessageDialog(this,
                "Sumber air baru berhasil ditambahkan!");

            muatDataSumberAir();

            jTextField3.setText("");
            jComboBox2.setSelectedIndex(-1);
            jTextField2.setText("");
            jComboBox1.setSelectedIndex(-1);
        } catch (SQLException ex) {
            logger.log(java.util.logging.Level.SEVERE,
                "Kesalahan saat menambah sumber air", ex);
            javax.swing.JOptionPane.showMessageDialog(this,
                "Terjadi kesalahan saat menambah sumber air.\n" + ex.getMessage(),
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        try {
            int selectedRow = jTable1.getSelectedRow();
            if (selectedRow == -1) {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Pilih data yang ingin diubah!");
                return;
            }

            if (jTextField3.getText().trim().isEmpty() ||
                jComboBox2.getSelectedItem() == null ||
                jTextField2.getText().trim().isEmpty() ||
                jComboBox1.getSelectedItem() == null) {

                javax.swing.JOptionPane.showMessageDialog(this,
                    "Semua field termasuk status harus diisi!",
                    "Input Tidak Lengkap",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }

            int id = (int) jTable1.getValueAt(selectedRow, 0);
            model.sumberAir sumber = new model.sumberAir();
            sumber.setIdSumber(id);
            sumber.setNamaSumber(jTextField3.getText().trim());
            sumber.setJenisSumber((String) jComboBox2.getSelectedItem());
            sumber.setStatus((String) jComboBox1.getSelectedItem());
            sumber.setLokasi(jTextField2.getText().trim());

            dao.sumberAirDao dao = new dao.sumberAirDao();
            dao.update(sumber);

            javax.swing.JOptionPane.showMessageDialog(this,
                "Data sumber air berhasil diperbarui!");

            muatDataSumberAir();

            jTextField3.setText("");
            jComboBox2.setSelectedIndex(-1);
            jTextField2.setText("");
            jComboBox1.setSelectedIndex(-1);
            jTable1.clearSelection();

        } catch (SQLException ex) {
            logger.log(java.util.logging.Level.SEVERE,
                "Kesalahan saat memperbarui data", ex);
            javax.swing.JOptionPane.showMessageDialog(this,
                "Terjadi kesalahan saat memperbarui data.\n" + ex.getMessage(),
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Pilih data yang ingin dihapus!");
            return;
        }

        int id = (int) jTable1.getValueAt(selectedRow, 0);
        int konfirmasi = javax.swing.JOptionPane.showConfirmDialog(this,
            "Yakin ingin menghapus data ini?",
            "Konfirmasi Hapus",
            javax.swing.JOptionPane.YES_NO_OPTION);

        if (konfirmasi == javax.swing.JOptionPane.YES_OPTION) {
            try {
                dao.sumberAirDao dao = new dao.sumberAirDao();
                dao.delete(id);

                javax.swing.JOptionPane.showMessageDialog(this,
                    "Data sumber air berhasil dihapus!");

                muatDataSumberAir();

                jTextField3.setText("");
                jComboBox2.setSelectedIndex(-1);
                jTextField2.setText("");
                jComboBox1.setSelectedIndex(-1);
                jTable1.clearSelection();

            } catch (SQLException ex) {
                logger.log(java.util.logging.Level.SEVERE,
                    "Kesalahan saat menghapus data", ex);
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Terjadi kesalahan saat menghapus data.\n" + ex.getMessage(),
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void muatDataSumberAir() {
    try {
        dao.sumberAirDao dao = new dao.sumberAirDao();
        java.util.List<model.sumberAir> daftarSumber = dao.getAll();

        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); 

        for (model.sumberAir s : daftarSumber) {
            model.addRow(new Object[]{
                s.getIdSumber(),
                s.getNamaSumber(),
                s.getJenisSumber(),
                s.getStatus(),
                s.getLokasi()
            });
        }

        jTextField3.setText("");
        jComboBox2.setSelectedIndex(-1);
        jTextField2.setText("");
        jComboBox1.setSelectedIndex(-1);
        jTable1.clearSelection();
        
        javax.swing.table.TableColumnModel kolom = jTable1.getColumnModel();
        kolom.getColumn(0).setPreferredWidth(40);   
        kolom.getColumn(1).setPreferredWidth(150);  
        kolom.getColumn(2).setPreferredWidth(80);  
        kolom.getColumn(3).setPreferredWidth(90); 
        kolom.getColumn(4).setPreferredWidth(120);  

    jTable1.getTableHeader().setResizingAllowed(false);
    jTable1.getTableHeader().setReorderingAllowed(false);

    javax.swing.table.TableRowSorter<javax.swing.table.DefaultTableModel> sorter = 
            new javax.swing.table.TableRowSorter<>(model);
        jTable1.setRowSorter(sorter);
    
    } catch (SQLException ex) {
        logger.log(java.util.logging.Level.SEVERE, "Gagal memuat data sumber air", ex);
        javax.swing.JOptionPane.showMessageDialog(this,
            "Gagal memuat data sumber air.\n" + ex.getMessage(),
            "Kesalahan Database",
            javax.swing.JOptionPane.ERROR_MESSAGE);
    }
}

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new formSumberAir().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
