/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view1;

import dao.laporanDao;
import java.sql.SQLException;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ravinaeka
 */
public class kelolaLaporan extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(kelolaLaporan.class.getName());

    /**
     * Creates new form listLaporan
     */
    public kelolaLaporan() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent e) {
                if (e.getClickCount() == 2) {
                    int selectedRow = jTable1.getSelectedRow();
                    if (selectedRow != -1) {
                        String nama = jTable1.getValueAt(selectedRow, 1).toString();
                        String kab = jTable1.getValueAt(selectedRow, 2).toString();
                        String kec = jTable1.getValueAt(selectedRow, 3).toString();
                        String tanggal = jTable1.getValueAt(selectedRow, 4).toString();
                        String deskripsi = jTable1.getValueAt(selectedRow, 5).toString();
                        String status = jTable1.getValueAt(selectedRow, 6).toString();

                        javax.swing.JOptionPane.showMessageDialog(
                            kelolaLaporan.this,
                            "Nama Warga : " + nama + 
                            "\nKabupaten/Kota : " + kab + 
                            "\nKecamatan : " + kec + 
                            "\nTanggal Laporan : " + tanggal + 
                            "\n\nDeskripsi :\n" + deskripsi + 
                            "\n\nStatus : " + status,
                            "Detail Laporan Warga",
                            javax.swing.JOptionPane.INFORMATION_MESSAGE
                        );
                    }
                }
            }
        });
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(50); 
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(50);  
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(80);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(300);
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(80);
        muatDataLaporan();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        jLabel2.setText("LAPORAN WARGA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID ", "Nama Warga", "Kabupaten/Kota", "Kecamatan", "Deskripsi", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 110, 870, 390));

        jButton1.setBackground(new java.awt.Color(166, 166, 166));
        jButton1.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jButton1.setText("Tindak");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 80, 140, -1));

        jButton2.setBackground(new java.awt.Color(166, 166, 166));
        jButton2.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jButton2.setText("Kembali");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 510, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view1/eimg list laporan.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1026, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                                   
    int selectedRow = jTable1.getSelectedRow();

    Object statusObj = jTable1.getValueAt(selectedRow, 6);
    Object kabupatenObj = jTable1.getValueAt(selectedRow, 2);
    Object kecamatanObj = jTable1.getValueAt(selectedRow, 3);

    String status = statusObj != null ? statusObj.toString() : "-";
    String kabupatenLaporan = kabupatenObj != null ? kabupatenObj.toString() : "-";
    String kecamatanLaporan = kecamatanObj != null ? kecamatanObj.toString() : "-";

    if (kabupatenLaporan.equals("-") || kecamatanLaporan.equals("-")) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Laporan ini tidak memiliki data daerah lengkap, tidak bisa ditindak.",
            "Data Tidak Lengkap",
            javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    if (status.equalsIgnoreCase("Sudah Ditindak")) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Laporan ini sudah ditindak sebelumnya.",
            "Informasi",
            javax.swing.JOptionPane.INFORMATION_MESSAGE);
        return;
    }


    dao.adminDao daoAdmin = new dao.adminDao();
    model.daerah daerahAdmin = daoAdmin.getDaerahAdmin(menuAdmin.idAdminLogin);

    if (daerahAdmin == null) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Gagal memuat data daerah admin.",
            "Error",
            javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (!kabupatenLaporan.equalsIgnoreCase(daerahAdmin.getKotaKabupaten()) ||
        !kecamatanLaporan.equalsIgnoreCase(daerahAdmin.getKecamatan())) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Anda tidak dapat menindak laporan dari daerah lain.",
            "Akses Ditolak",
            javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }


int konfirmasi = javax.swing.JOptionPane.showConfirmDialog(this,
    "Laporan ini berasal dari daerah Anda.\nApakah Anda ingin menindak lanjut laporan ini?",
    "Konfirmasi Tindak",
    javax.swing.JOptionPane.YES_NO_OPTION,
    javax.swing.JOptionPane.QUESTION_MESSAGE);

if (konfirmasi == javax.swing.JOptionPane.YES_OPTION) {
        try {
            int idLaporan = Integer.parseInt(jTable1.getValueAt(selectedRow, 0).toString());
            String namaWarga = jTable1.getValueAt(selectedRow, 1).toString();
            String kabupaten = jTable1.getValueAt(selectedRow, 2).toString();
            String kecamatan = jTable1.getValueAt(selectedRow, 3).toString();
            
            view1.formDistribusiAir form = new view1.formDistribusiAir();
            form.setDataLaporan(idLaporan, namaWarga, kabupaten, kecamatan);
            form.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            System.getLogger(kelolaLaporan.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new menuAdmin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

        private void muatDataLaporan() {
           laporanDao dao = new laporanDao();
           List<model.laporan1> daftarLaporan = dao.getAll();

           DefaultTableModel model = new DefaultTableModel(
               new Object[]{"ID", "Nama Warga", "Kabupaten/Kota", "Kecamatan", "Tanggal Laporan", "Deskripsi", "Status"}, 0
           ) {
               @Override
                public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        for (model.laporan1 l : daftarLaporan) {
            model.addRow(new Object[]{
                l.getIdLaporan(),
                l.getNamaPengguna(),
                l.getKotaKabupaten(),
                l.getKecamatan(),
                l.getTanggalLaporan(),
                l.getDeskripsi(),
                l.getStatus()
            });
        }

        jTable1.setModel(model);
        jTable1.setAutoCreateRowSorter(true); 
        
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(90);  
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(140);  
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(150);  
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(150);  
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(180);  
        jTable1.getColumnModel().getColumn(5).setPreferredWidth(200);  
        jTable1.getColumnModel().getColumn(6).setPreferredWidth(130);  
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new kelolaLaporan().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
