/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view1;

import dao.laporanDao;
import model.laporan1;
import javax.swing.table.DefaultTableModel;
import java.awt.HeadlessException;
import java.sql.Date;
import java.time.LocalDate;
import java.time.format.DateTimeParseException;

public class laporan extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(laporan1.class.getName());

    /**
     * Creates new form laporam
     */
    public laporan() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);

        jTextField2.setText("YYYY-MM-DD");
        jTextField2.setForeground(java.awt.Color.GRAY);

        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {
                if (jTextField2.getText().equals("YYYY-MM-DD")) {
                    jTextField2.setText("");
                    jTextField2.setForeground(java.awt.Color.BLACK);
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
                if (jTextField2.getText().isEmpty()) {
                    jTextField2.setText("YYYY-MM-DD");
                    jTextField2.setForeground(java.awt.Color.GRAY);
                }
            }
        });

        muatDataLaporan();
    jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            if (evt.getClickCount() == 2) { 
                int selectedRow = jTable1.getSelectedRow();
                if (selectedRow != -1) {
                    Object deskripsiObj = jTable1.getValueAt(selectedRow, 1);
                    if (deskripsiObj != null) {
                        String deskripsi = deskripsiObj.toString();
                        
                        javax.swing.JTextArea area = new javax.swing.JTextArea(deskripsi);
                        area.setWrapStyleWord(true);
                        area.setLineWrap(true);
                        area.setEditable(false);
                        javax.swing.JScrollPane scrollPane = new javax.swing.JScrollPane(area);
                        scrollPane.setPreferredSize(new java.awt.Dimension(400, 200));

                        javax.swing.JOptionPane.showMessageDialog(
                            laporan.this,
                            scrollPane,
                            "Deskripsi Lengkap",
                            javax.swing.JOptionPane.INFORMATION_MESSAGE
                        );
                    }
                }
            }
        }
}   );
}

    
private void muatDataLaporan() {
    laporanDao dao = new laporanDao();
    java.util.List<laporan1> daftarLaporan = dao.getAll();

    javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(
        new Object[]{"Tanggal Laporan", "Deskripsi", "Status"}, 0
    ) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; 
        }
    };

    for (laporan1 l : daftarLaporan) {
        model.addRow(new Object[]{
            l.getTanggalLaporan(),
            l.getDeskripsi(),
            l.getStatus()
        });
    }

    jTable1.setModel(model);

    jTable1.getTableHeader().setReorderingAllowed(false);
    jTable1.getTableHeader().setResizingAllowed(false);

    jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

    jTable1.setAutoCreateRowSorter(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        jLabel2.setText("LAPORAN");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel3.setText("Tanggal:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel4.setText("Deskripsi:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 180, -1, -1));

        jTextField2.setForeground(new java.awt.Color(128, 128, 128));
        jTextField2.setText("YYYY-MM-DD");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 130, 240, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Tanggal Laporan", "Deskripsi", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 570, 410));

        jButton1.setBackground(new java.awt.Color(108, 153, 194));
        jButton1.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jButton1.setText("Kirim");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 290, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 180, 240, 100));

        jButton2.setBackground(new java.awt.Color(166, 166, 166));
        jButton2.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jButton2.setText("Kembali");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 500, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view1/eimg laporan.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1026, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            new menuWarga().setVisible(true);
            this.dispose();
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Gagal membuka menu warga: " + e.getMessage(),
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                                                    
    try {
        String tanggalInput = jTextField2.getText().trim();

        if (tanggalInput.equals("YYYY-MM-DD") || tanggalInput.isEmpty()) {
            throw new IllegalArgumentException("Tanggal tidak boleh kosong!");
        }

        LocalDate parsedDate = LocalDate.parse(tanggalInput);

        laporan1 l = new laporan1();
        l.setIdPengguna(menuWarga.idWargaLogin);
        l.setIdDaerah(menuWarga.idDaerahWarga);
        l.setTanggalLaporan(Date.valueOf(parsedDate));
        l.setDeskripsi(jTextArea1.getText());
        l.setStatus("Belum Ditindak");
        new dao.laporanDao().insert(l);
        javax.swing.JOptionPane.showMessageDialog(this, "Laporan berhasil dikirim!");
        muatDataLaporan();

        jTextField2.setText("YYYY-MM-DD");
        jTextField2.setForeground(java.awt.Color.GRAY);
        jTextArea1.setText("");

    } catch (DateTimeParseException e) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "Format tanggal salah! Gunakan format YYYY-MM-DD yang valid.",
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
    } catch (HeadlessException | IllegalArgumentException e) {
        javax.swing.JOptionPane.showMessageDialog(this,
                e.getMessage(),
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    
    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new view1.laporan().setVisible(true));
   
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
