/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view1;

import dao.distribusiAirDao;
import dao.sumberAirDao;
import dao.daerahDao;
import java.sql.SQLException;
import model.distribusiAir;
import model.sumberAir;
import model.daerah;
import javax.swing.table.DefaultTableModel;
import java.util.List;

public class listDistribusiAir extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(listDistribusiAir.class.getName());

    /**
     * Creates new form listDistribusiAir
     */
    public listDistribusiAir() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(80); 
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(80);  
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(180);
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowActivated(java.awt.event.WindowEvent e) {
                muatDataDistribusi();
            }
        });
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        jLabel2.setText("RIWAYAT DISTRIBUSI");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID ", "Nama Sumber", "Kecamatan", "Tanggal Distribusi", "Volume "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setPreferredSize(new java.awt.Dimension(255, 80));
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 110, 880, 380));

        jButton1.setBackground(new java.awt.Color(166, 166, 166));
        jButton1.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jButton1.setText("Kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 500, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view1/eimg list distribusi air.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1026, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new menuWarga().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void muatDataDistribusi() {
    try {
        distribusiAirDao distribusiDao = new distribusiAirDao();
        sumberAirDao sumberDao = new sumberAirDao();
        daerahDao daerahDao = new daerahDao();

        int idDaerahWarga = menuWarga.idDaerahWarga;
        System.out.println("🟢 ID daerah warga login: " + idDaerahWarga);

        List<distribusiAir> daftarDistribusi = distribusiDao.getByDaerah(idDaerahWarga);
        System.out.println("📋 Jumlah distribusi ditemukan: " + daftarDistribusi.size());

        DefaultTableModel model = new DefaultTableModel(
            new Object[]{"ID", "Nama Sumber", "Kecamatan", "Tanggal Distribusi", "Volume Distribusi"}, 0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        for (distribusiAir d : daftarDistribusi) {
            String namaSumber = "-";
            String kecamatan = "-";

            try {
                sumberAir sumber = sumberDao.getById(d.getIdSumber());
                if (sumber != null) {
                    namaSumber = sumber.getNamaSumber();
                }

                daerah daerahObj = daerahDao.getById(d.getIdDaerah());
                if (daerahObj != null) {
                    kecamatan = daerahObj.getKecamatan();
                }
            } catch (SQLException e) {
                System.err.println("⚠️ Gagal memuat detail distribusi: " + e.getMessage());
            }

            model.addRow(new Object[]{
                d.getIdDistribusi(),
                namaSumber,
                kecamatan,
                d.getTanggalDistribusi(),
                (long) d.getVolumeDistribusi()
            });
        }

        jTable1.setModel(model);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.getTableHeader().setResizingAllowed(false);

        javax.swing.table.TableRowSorter<javax.swing.table.DefaultTableModel> sorter =
                new javax.swing.table.TableRowSorter<>(model);
        jTable1.setRowSorter(sorter);

    } catch (SQLException e) {
        javax.swing.JOptionPane.showMessageDialog(
            this,
            "Gagal memuat data distribusi: " + e.getMessage(),
            "Kesalahan Database",
            javax.swing.JOptionPane.ERROR_MESSAGE
        );
    }
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new listDistribusiAir().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
